services:
    postgres:
        image: postgres:13.18-alpine3.21
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        networks:
            - 'default'
